---
- hosts: all
  tasks:
    - name: JAVA | Installing java
      become: yes
      yum:
       name: java-1.8.0-openjdk
    - name: WGET | Installing wget
      become: yes
      yum:
       name: wget
    - name: TOMCAT | Installing tomcat
      command: /bin/sudo su
      command: /bin/wget http://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz
      command: /bin/tar -zxpvf apache-tomcat-8.5.6.tar.gz -C /opt/
      command: /bin/cd /opt/
      command: /bin/mv tar -zxpvf apache-tomcat-8.5.6/ tomcat
      command: /bin/echo "export CATALINA_HOME='/opt/tomcat/'" >> ~/.bashrc
      command: /bin/source ~/.bashrc
      template: src=tomcat-users.xml dest=/opt/tomcat/conf/tomcat-users.xml
      command: /bin/cd /opt/tomcat/bin/
      command: /bin/sh ./startup.sh
      command: /bin/sh ./shutdown.sh
      command: /bin/firewall-cmd --permanent --zone=public --add-port=8080/tcp
      command: /bin/firewall-cmd --reload
#    - name: TOMCAT | Installing tomcat
#      
#      
#      
#      
